# Generated by Django 3.1.7 on 2021-03-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NA', 'North America'), ('SA', 'South America'), ('AN', 'Antartica'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('AU', 'Australia')], default='EU', max_length=2)),
                ('population', models.PositiveBigIntegerField()),
                ('area', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('population', models.PositiveBigIntegerField()),
                ('area', models.PositiveBigIntegerField()),
                ('number_of_hospitals', models.PositiveBigIntegerField()),
                ('number_of_schools', models.PositiveBigIntegerField()),
                ('number_of_national_parks', models.PositiveIntegerField()),
                ('number_of_rivers', models.PositiveIntegerField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wookiadmin.continent')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('population', models.PositiveBigIntegerField()),
                ('area', models.PositiveBigIntegerField()),
                ('number_of_roads', models.PositiveBigIntegerField()),
                ('number_of_trees', models.PositiveBigIntegerField()),
                ('number_of_schools', models.PositiveBigIntegerField()),
                ('number_of_shops', models.PositiveBigIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wookiadmin.country')),
            ],
        ),
    ]
