version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  

  zookeeper:
    image: zookeeper:3.4.9
    volumes:
      - ./volumes/zookeeper/data:/data
     
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    volumes:
      - ./volumes/kafka/data:/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_BROKER_ID: 1